export interface Clientes {	
Id_Cliente: number,
Cargador: string,
Cod_TipoCliente: string,
Des_Cliente: string,
Dir_Cliente: string,
Ref_Cliente: string,
Cod_Ubigeo: string,
Cod_Estado: string,
Latitud: number,
Longitud: number,
DNI_Contacto: string,
Nombre_Contacto: string,
Celular_Contacto: string,
Email_Contacto: string,
CuentaWeb: string,
Contraseña: string,
PIN_Claro: string,
PIN: string,
Fecha_Alta: Date,
Id_Vendedor: number,
Obs_Bodega: string,
Flag_EmailValido: boolean      
}